sudo: false
language: go
cache:
  directories:
  - $HOME/.cache/bazel
env:
  global:
    - BAZEL_VERSION=0.21.0
before_install:
  - |
    sysctl kernel.unprivileged_userns_clone=1
    wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
script:
  - |
    bazel \
      --host_jvm_args=-Xmx8000m \
      --host_jvm_args=-Xms8000m \
      build \
      --config=ci \
      --local_resources=8500,2,1.0 \
      :plexbackup
