name: CI
on:
- push
- pull_request
- workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        bazelisk build --config=ci //...
        mkdir out
        bin/release out
        bazelisk run //:plexbackup -- --version
