name: CI
on:
- push
- pull_request
- workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - linux_amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Determine package version
      run: |
        readonly GIT_DESCRIBE=$(git describe --always --tags --dirty)
        echo $GIT_DESCRIBE
        echo "pkg_version=${GIT_DESCRIBE#v}" >> $GITHUB_ENV
    - name: Build
      run: |
        bazelisk build --config=ci --platforms @io_bazel_rules_go//go/toolchain:${{ matrix.toolchain }} //:archive
        echo "archive=$(bazelisk info bazel-bin)/archive.tar.gz" >> $GITHUB_ENV
        echo $pkg_version
    - name: Upload binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: plexbackup-${{ env.pkg_version }}-${{ matrix.toolchain }}.tar.gz
        path: ${{ env.archive }}
