name: CI
on:
- push
- pull_request
- workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - linux_amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        readonly DESCRIBE=$(git describe --always --tags --dirty)
        readonly VERSION=${DESCRIBE#v}
        bazelisk build --config=ci --platforms @io_bazel_rules_go//go/toolchain:${{ matrix.toolchain }} //:archive
        bazelisk run //:plexbackup -- --version
        mv $(bazelisk info bazel-bin)/archive.tar.gz plexbackup-${VERSION}-${{ matrix.toolchain }}.tar.gz
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.toolchain }}
        path: plexbackup-${VERSION}-${{ matrix.toolchain }}.tar.gz
