name: CI
on:
- push
- pull_request
- workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - linux_amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        readonly DESCRIBE=$(git describe --always --tags --dirty)
        readonly VERSION=${DESCRIBE#v}
        echo "version=$VERSION" >> $GITHUB_ENV
        bazelisk build --config=ci --platforms @io_bazel_rules_go//go/toolchain:${{ matrix.toolchain }} //:archive
        echo "archive=$(bazelisk info bazel-bin)/archive.tar.gz" >> $GITHUB_ENV
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: plexbackup-${{ env.version }}-${{ matrix.toolchain }}.tar.gz
        path: ${{ env.archive }}
