name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # approximates Plex Media Server platform availability
        goos: [windows, linux, darwin]
        goarch: [amd64]
        goarm: ['']
        include:
        - goos: linux
          goarch: arm
          goarm: 7
        - goos: linux
          goarch: arm64
          goarm: ''
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0  # static binary
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.2
    - run: make dist
    - id: vars
      run: echo "distpath=$(make distpath)" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.vars.outputs.distpath }}
        path: ${{ steps.vars.outputs.distpath }}
    - run: sha256sum ${{ steps.vars.outputs.distpath }} > ${{ steps.vars.outputs.distpath }}.sha256
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.vars.outputs.distpath }}.sha256
        path: ${{ steps.vars.outputs.distpath }}.sha256
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - uses: softprops/action-gh-release@v2
      with:
        draft: true
        prerelease: ${{ contains(github.ref, '-') }}
        files: |
          artifacts/*/*
